#!/bin/bash
#
# This script will only run on a computer using the IP
# address: 58.60.1.71.
#
# This auto-generated script was downloaded from http://iotta.snia.org.
# It will download the 12 subtraces of FIU IODedup
#
echo "Downloading the 12 subtraces of FIU IODedup" 1>&2
cookies=$(mktemp)
cat >> $cookies << 'EOF'
# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by iotta.snia.org! Edit at your own risk.

.iotta.snia.org	TRUE	/	FALSE	0	infodigest	095922bd4cbaeed73e7fe06ac9c4b3cf66321556
.iotta.snia.org	TRUE	/	FALSE	0	legal	true
.iotta.snia.org	TRUE	/	FALSE	0	id	908978
.iotta.snia.org	TRUE	/	FALSE	0	user_ip	58.60.1.71
EOF

if which wget >/dev/null 2>&1; then
  useWGET=true
elif which curl >/dev/null 2>&1; then
  useCURL=true
else
  echo "Couldn't find either wget or curl. Please install one of them" 1>&2
  exit 1
fi

checkForError() {
  delete=false
  if $useWGET && (( $1 == 2 || $1 == 3 || $1 == 5 || $1 == 7 || $1 == 8 ))
  then
    delete=true
  elif $useWGET && [ ! -s "$2" ]
  then
    delete=true
  elif $useCURL && (( $1 == 22 || $1 == 36 ))
  then
    delete=true
  fi
}

downloadFile() {
  file=$1
  id=$2
  echo "Start Downloading" "$file"
  url="http://server2.iotta.snia.org/traces/block-io/$id/download?type=file&sType="
  if $useWGET; then
    wget --content-on-error --load-cookies=$cookies -O "$file" -c "$url""wget"
    error=$?
  elif $useCURL; then
    curl -s -f -b $cookies -o "$file" -C - -L "$url""curl"
    error=$?
    if [ $error -eq 22 ]; then
      curl -s -b $cookies -o "$file" -C - -L "$url""curl"
    fi
  fi

  if [ $error -eq 0 ]; then
    echo "Finished Downloading $file"
  else
    checkForError $error "$file"
    downloadLink="http://iotta.snia.org/downloaderinfos/new?trace_id=391&type=subtracesViaScript&sType=&came_from=iotta.snia.org"
    if $delete; then
      echo "There was an error downloading the file ($file)"
      if grep "internal iotta error: ip mismatch" "$file" > /dev/null; then
        echo "This script will only run on a computer with the IP address 113.249.213.177."
        grep "Your current IP address is" "$file"
        echo "Please use the following link to fill out the download license form with your current IP address and run the new script:"
        echo "$downloadLink"
      elif grep "internal iotta error: invalid cookie" "$file" > /dev/null; then
        echo "Invalid cookie, please use the following link to fill out the form and try again:"
        echo "$downloadLink"
      fi
      rm -f "$file"
    else
      echo "$file was only partially downloaded."
    fi
    echo "Stopping..."
    exit 1
  fi
}

mkdir -p ~/Downloads/FIU_Traces


cd ~/Downloads/FIU_Traces || exit 
downloadFile "homes.tar.gz" 402
downloadFile "web-vm.tar.gz" 403
downloadFile "mail-01.tar.gz" 392 
# downloadFile "mail-02.tar.gz" 393
# downloadFile "mail-03.tar.gz" 394
# downloadFile "mail-04.tar.gz" 395
# downloadFile "mail-05.tar.gz" 396
# downloadFile "mail-06.tar.gz" 397
# downloadFile "mail-07.tar.gz" 398
# downloadFile "mail-08.tar.gz" 399
# downloadFile "mail-09.tar.gz" 400
# downloadFile "mail-10.tar.gz" 401
cd - || exit 

echo "Finished All Downloads"
rm -f $cookies
